# Training and Testing of Artificial Neural Networks

In [5]:
import numpy as np

## MADALINE

This is a 2 layered artificial neural network. In which, only first weight layer is trainable second layer is kept fixed. Also, it can have only on output unit. `MADALINE.py` contains a general model for **MADALINE**. First we will import model here:

In [ ]:
from MADALINE import MADALINE

Next, we will define an instance of the model with 4 input units and 7 hidden units:

In [ ]:
model = MADALINE(2, 2)

We can see what all variables the `model` contains:

In [ ]:
print(vars(model))

From above output, we can see that the model has 4 member variables namely, **W1**, **W2**, **b1** and **b2**. These corresponds to the weights for first layer, weights for second layer, biases for hidden layer and bias for output layer. Apart from these we have one more member variable **sum** which will be used to save the sums calculated while forward pass for hidden layer and this will be used to change the weights later while backpropagation.

To do the calculations manually, I will reinitiaze weights of **model** so that we wouldn't get random weights

In [ ]:
model.W1 = np.array([[0.1, 0.2], [0.3, 0.4]])
model.b1 = np.array([[0.5], [0.5]])
model.W2 = np.array([[0.5, 0.6]])
model.b2 = np.array([[0.5]])

In [ ]:
print(vars(model))

I am going train the model to mimic XOR gate so for that we need to make data to pass through the neural net to learn.

In [ ]:
data = [(np.array([[1], [1]]), np.array([[-1]])), 
        (np.array([[1], [-1]]), np.array([[1]])), 
        (np.array([[-1], [1]]), np.array([[1]])), 
        (np.array([[-1], [-1]]), np.array([[-1]]))]
print(data)

Time to train the Madaline net, to show the weights I will train the net for each epoch separately instead of training for multiple epochs at once with 0.5 learning rate.

In [ ]:
model.train(data, 0.5, 1)

In [ ]:
model.W1

Here the accuracy is 50% only which is of no use since the model behaving like a random predicting model, so we need to train it more, but first we will lool into the weights since they might have changed during above epoch

In [ ]:
model.W1

In [ ]:
model.b1

In [ ]:
model.W2

In [ ]:
model.b2

We can see the first layer weights have been changed, whereas the weights for the second layer is same. Now, we will do next epoch and ee what is the result:

In [ ]:
model.train(data, 5, 100)

In [ ]:
model.W1

## Kohonen Neural Network

This is an unsupersived neural network. It can be used to cluster the given inputs into specified number of outputs. To make clusters this model uses **Euclidean distance**.

In [ ]:
from Kohonen import KohonenNN

In [ ]:
model1 = KohonenNN(2, 2)

In [ ]:
print(vars(model1))

The member variable of the KohonenNN is **W**, which corresponds to the weights between input layer and the output layer and will be used to calculate the **Euclidean distance**.

As in the previous model we will again set the weights explicily to see the behaviour properly

In [ ]:
model1.W = np.array([[0.1, 0.2], [0.3, 0.4]])
print(model1.W)

First, we need to prepare the data for the model. We will use the same data as above but her we do not need the output values or desired values.

In [ ]:
data = [np.array([[1], [1]]), 
        np.array([[1], [-1]]),
        np.array([[-1], [1]]),
        np.array([[-1], [-1]])]
print(data)

I have designed the model such that we can get the clusters directly:

In [ ]:
model1.cluster([data[0]], learning_rate=0.5, R=1, R_decay=0.5, lr_decay= 0.5, epochs=1)

## Backprop Neural Network

In [1]:
from BackpropNN import BackpropNN

In [2]:
model2 = BackpropNN(2, 2, 1, 0.5)

In [3]:
print(vars(model2))

{'Wi': array([[ -1.53665052, -10.04926768],
       [ -2.83549619,   1.74004336]]), 'bi': array([[5.87865058],
       [8.73610592]]), 'Wh': array([[-3.69220453, 24.34201821]]), 'bh': array([[3.43472757]]), 's': 0.5}


Again we will set weights explicitly

In [13]:
model2.Wi = np.array([[0.1, 0.2], [0.3, 0.4]])
model2.bi = np.array([[-0.5], [-0.5]])
model2.Wh = np.array([[0.5, 0.6]])
model2.bh = np.array([[-0.5]])

Prepared data:

In [7]:
data = [(np.array([[0.4], [0.5]]), np.array([[0.9]])),
       (np.array([[0.3], [0.4]]), np.array([[0.7]])),
       (np.array([[0.2], [0.3]]), np.array([[0.5]])),
       (np.array([[0.1], [0.2]]), np.array([[0.9]]))
       ]
print(data)

[(array([[0.4],
       [0.5]]), array([[0.9]])), (array([[0.3],
       [0.4]]), array([[0.7]])), (array([[0.2],
       [0.3]]), array([[0.5]])), (array([[0.1],
       [0.2]]), array([[0.9]]))]


In [14]:
model2.train([data[0]], learning_rate=0.05, epochs=1)
print(model2.Wi)
print(model2.bi)
print(model2.Wh)
print(model2.bh)

[[-0.00246892 -0.00308616]
 [-0.00298073 -0.00372592]]
Epoch: 1
Loss: 0.15859613293467442

#----------------------------------------------------------------#

[[0.10012345 0.20015431]
 [0.30014904 0.4001863 ]]
[[-0.49969138]
 [-0.49962741]]
[[0.50226557 0.60237705]]
[[-0.49502205]]


In [ ]:
for (x, y) in data:
    print(model2.predict(x))